### ISSUE TITLE
Burn Sample Payload

### ISSUE THREAD

**Issue by varun7447** [rstropek/Samples#1]
First of all excellent resource and i really like this repo. 

I have a question related to Burn Payload example. Do you know if we can use * wilcard in payload. My requirement is, i have bunch of files ending with *.lic. When i install the exe the *.lic files has to be copied over to the installation location. This way we can control before running what *.lic can exist next to the exe in the same directory so that the files get installed. Do you know if we can do this?

Note: I am able to use CopyFile element in MSI and it works great. When i bundle the same MSI into an exe the *.lic files are not copied. I can think only one reason for this problem, burn caches the installer to a location other than the sourcedirectory and all *.lic files are not available in the cache location so they are not being copied. Not sure how to avoid this problem

**Comment by rstropek** [comment]
Unfortunately I don't know the answer to your question. According to [the WiX documentation](http://wixtoolset.org/documentation/manual/v3/xsd/wix/payload.html), `Payload` wants the *Location of the source file*. It does not say anything about wildcard support. I don't think wildcards are support in `Payload` but I have not tried it. Hope this helps.

**Comment by varun7447** [comment]
Thanks Rainer!! One another question, do you know if there is any setting that I can use in burn to copy the payload files? The wildcards are not working with bundle but works fine with msi. Since bundle caches the file someplace, do you know I can execute the exe from the same location as the initial exe?

**Comment by rstropek** [comment]
Unfortunately I don't fully understand your question. You are writing a custom bootstrapper written with WPF and you need to provide some payload for it to run. Is that correct?

**Comment by varun7447** [comment]
Here is what I am trying to do.

1) need to copy the *lic files to the installfolder. The reason for wildcard is the installer is user specific and we don't know what *.lic we will have at the install time.

Using copyelement in setup project I was able to copy *.lic files from Sourcedir. Copyelement supports wild card. 

When I bundle the setup project the Copyelement no longer works. So was wondering what I am doing wrong.
